// =====================================================
// AUTO-GENERATED - DO NOT EDIT MANUALLY
// Generated by: terraform-local/generate_flutter_config_local.ps1
// For: Local Docker Development
// Generated: 2026-02-06 18:51:27
// =====================================================

class AwsConfig {
  // LOCAL DEVELOPMENT ENDPOINTS
  // Using Docker containers on localhost
  
  /// Availability Service (localhost:8000)
  static const String availabilityUrl = 'http://localhost:8000';
  
  /// Order Service (localhost:8001)
  static const String orderUrl = 'http://localhost:8001';
  
  /// Environment indicator
  static const String environment = 'local';
  
  /// Is production flag
  static const bool isProduction = false;
}
