# =====================================================
# LOCAL FLUTTER CONFIG GENERATOR
# =====================================================
# Generates aws_config.dart for local Docker development
# 
# USAGE: .\generate_flutter_config_local.ps1
# =====================================================

Write-Host "`n====================================================" -ForegroundColor Cyan
Write-Host "   LOCAL FLUTTER CONFIG GENERATOR" -ForegroundColor Cyan
Write-Host "====================================================" -ForegroundColor Cyan

# Local Docker endpoints
$LOCAL_AVAILABILITY_URL = "http://localhost:8000"
$LOCAL_ORDER_URL = "http://localhost:8001"

$flutterConfigPath = Join-Path $PSScriptRoot "..\rapid_delivery_app\lib\aws_config.dart"

# Generate the Dart config file
$configContent = @"
// =====================================================
// AUTO-GENERATED - DO NOT EDIT MANUALLY
// Generated by: terraform-local/generate_flutter_config_local.ps1
// For: Local Docker Development
// Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
// =====================================================

class AwsConfig {
  // LOCAL DEVELOPMENT ENDPOINTS
  // Using Docker containers on localhost
  
  /// Availability Service (localhost:8000)
  static const String availabilityUrl = '$LOCAL_AVAILABILITY_URL';
  
  /// Order Service (localhost:8001)
  static const String orderUrl = '$LOCAL_ORDER_URL';
  
  /// Environment indicator
  static const String environment = 'local';
  
  /// Is production flag
  static const bool isProduction = false;
}
"@

# Write the file
Set-Content -Path $flutterConfigPath -Value $configContent -Encoding UTF8

Write-Host "`n[OK] Generated: $flutterConfigPath" -ForegroundColor Green
Write-Host "`n--- Configuration ---" -ForegroundColor Yellow
Write-Host "Availability URL: $LOCAL_AVAILABILITY_URL"
Write-Host "Order URL:        $LOCAL_ORDER_URL"
Write-Host "`n[NEXT STEPS]" -ForegroundColor Cyan
Write-Host "1. Ensure api_service.dart has: useAwsBackend = false"
Write-Host "2. Start Docker: cd local && docker-compose -f docker-compose-local.yaml up -d"
Write-Host "3. Seed data: python local/seed_local.py"
Write-Host "4. Run Flutter: cd rapid_delivery_app && flutter run -d chrome"
Write-Host ""
